### ISSUE TITLE
failed with a specific file 

### ISSUE THREAD

**Issue by neelgo** [AndersonMamede/merge-pdf-files#1]
Your work is awesome it just failed with specific file.
can you make it work with any pdf?

I think first two warnings are from pdf 1 but fatal error is on pdf 2
[1.pdf](https://github.com/AndersonMamede/merge-pdf-files/files/4605554/1.pdf)
[2.PDF](https://github.com/AndersonMamede/merge-pdf-files/files/4605555/2.PDF) 

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\xampp\htdocs\merge-pdf-files-master\tcpdf\tcpdf.php on line 17784

Warning: chr() expects parameter 1 to be int, string given in C:\xampp\htdocs\merge-pdf-files-master\tcpdf\include\tcpdf_fonts.php on line 1671

Fatal error: Uncaught Exception: This document (C:\xampp\htdocs\merge-pdf-files-master\test\2.PDF) probably uses a compression technique which is not supported by the free parser shipped with FPDI. (See https://www.setasign.com/fpdi-pdf-parser for more details) in C:\xampp\htdocs\merge-pdf-files-master\FPDI\pdf_parser.php:322 Stack trace: #0 C:\xampp\htdocs\merge-pdf-files-master\FPDI\pdf_parser.php(195): pdf_parser->_readXref(Array, 116) #1 C:\xampp\htdocs\merge-pdf-files-master\FPDI\fpdi_pdf_parser.php(64): pdf_parser->__construct('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\merge-pdf-files-master\FPDI\fpdi.php(135): fpdi_pdf_parser->__construct('C:\\xampp\\htdocs...') #3 C:\xampp\htdocs\merge-pdf-files-master\FPDI\fpdi.php(106): FPDI->_getPdfParser('C:\\xampp\\htdocs...') #4 C:\xampp\htdocs\merge-pdf-files-master\MergePdf.class.php(43): FPDI->setSourceFile('C:\\xampp\\htdocs...') #5 C:\xampp\htdocs\merge-pdf-files-master\MergePdf.class.php(38): MergePdf::addFile(Object(FPDI), 'test/2.pdf') #6 C:\xampp\htdocs\merge-pdf-fi in C:\xampp\htdocs\merge-pdf-files-master\FPDI\pdf_parser.php on line 322

**Comment by AndersonMamede** [comment]
This issue has been closed due to inactivity.
